export enum AppConfigEnum {
  MONGODB_CONNECTION_URL = "MONGODB_CONNECTION_URL",
  USER_POOL_ID = "USER_POOL_ID",
  CLIENT_ID = "CLIENT_ID",

  QUEUE_USER_CONFIRM_AUTH = "QUEUE-USER_CONFIRM_AUTH",
  AUTH_ACCESS_KEY_ID = "AUTH_ACCESS_KEY_ID",
  AUTH_SECRET_ACCESS_KEY = "AUTH_SECRET_ACCESS_KEY",
}
